This tutorial is taken from https://github.com/KeithGalli/pandas/tree/master
The video to this tutorial is here: https://youtu.be/vmEHCJofslg

## Loading data into Pandas

In [ ]:
# prompt: download the file https://github.com/KeithGalli/pandas/blob/master/pokemon_data.csv

import requests

def download_file(url, filename):
    try:
        response = requests.get(url, stream=True)
        response.raise_for_status()  # Raise an exception for bad status codes

        with open(filename, 'wb') as file:
            for chunk in response.iter_content(chunk_size=8192):
                file.write(chunk)
        print(f"File '{filename}' downloaded successfully.")

    except requests.exceptions.RequestException as e:
        print(f"Error downloading file: {e}")

# Example usage:
file_url = "https://raw.githubusercontent.com/KeithGalli/pandas/master/pokemon_data.csv" # Note: using raw content link
file_name = "pokemon_data.csv"

download_file(file_url, file_name)

File 'pokemon_data.csv' downloaded successfully.

In [ ]:
# prompt: open the downloaded file with pandas

import pandas as pd

# Assuming the file is named 'pokemon_data.csv' in the current directory
try:
  df = pd.read_csv('pokemon_data.csv', index_col='Name')
  print(df.head()) # Print the first few rows of the DataFrame
except FileNotFoundError:
  print("Error: 'pokemon_data.csv' not found. Please make sure the file exists in the current directory or provide the correct path.")
except pd.errors.ParserError:
    print("Error: Could not parse the CSV file. Please check the file format.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

                       # Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
Name
Bulbasaur              1  Grass  Poison  45      49       49       65
Ivysaur                2  Grass  Poison  60      62       63       80
Venusaur               3  Grass  Poison  80      82       83      100
VenusaurMega Venusaur  3  Grass  Poison  80     100      123      122
Charmander             4   Fire     NaN  39      52       43       60

                       Sp. Def  Speed  Generation  Legendary
Name
Bulbasaur                   65     45           1      False
Ivysaur                     80     60           1      False
Venusaur                   100     80           1      False
VenusaurMega Venusaur      120     80           1      False
Charmander                  50     65           1      False

## Accessing data

Read column headers:

In [ ]:
df.columns

Index(['#', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

Get a column as the `pandas.core.series.Series` object:

In [ ]:
df['HP']

Name
Bulbasaur                45
Ivysaur                  60
Venusaur                 80
VenusaurMega Venusaur    80
Charmander               39
                         ..
Diancie                  50
DiancieMega Diancie      50
HoopaHoopa Confined      80
HoopaHoopa Unbound       80
Volcanion                80
Name: HP, Length: 800, dtype: int64

Get a DataFrame containing just a subset of columns:

In [ ]:
print(type(df[['Type 1', 'Type 2', 'HP']]))

<class 'pandas.core.frame.DataFrame'>

Given that we've chosen `index_col='Name'` in `read_csv` above, we can use the pokemons' name as index. Note the usage of the `loc` method for selecting columns and rows. This method makes the selection based on predefined labels of the rows and columns. We will use this method a lot in this notebook!

In [ ]:
df.loc['Ivysaur']

#                  2
Type 1         Grass
Type 2        Poison
HP                60
Attack            62
Defense           63
Sp. Atk           80
Sp. Def           80
Speed             60
Generation         1
Legendary      False
Name: Ivysaur, dtype: object

The returned object is `pandas.Series`. We can access its elements using square brackets, e.g. `pokemon['Type 2']`:

In [ ]:
df.loc['Ivysaur']['Type 2']

'Poison'

The `iloc` method makes the columns and rows selection based on their position in the DataFrame. The position is numbered by an integer. The following code returns the third row in our DataFrame:

In [ ]:
df.iloc[2]

#                  3
Type 1         Grass
Type 2        Poison
HP                80
Attack            82
Defense           83
Sp. Atk          100
Sp. Def          100
Speed             80
Generation         1
Legendary      False
Name: Venusaur, dtype: object

Slicing rows with `iloc`:

In [ ]:
print(df.iloc[0:4])

Read the "cell" at coordinates [2,1] (row, column):

In [ ]:
print(df.iloc[2,1])

Select a subset of rows (just those where the pokemon's `Type 1` is `Grass`)

In [ ]:
df.loc[df['Type 1'] == "Grass"]

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Grass,Poison,80,100,123,122,120,80,1,False
Oddish,43,Grass,Poison,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...
Chespin,650,Grass,NaN,56,61,65,48,45,38,6,False
Quilladin,651,Grass,NaN,61,78,95,56,58,57,6,False
Chesnaught,652,Grass,Fighting,88,107,122,74,75,64,6,False
Skiddo,672,Grass,NaN,66,65,48,62,57,52,6,False
Gogoat,673,Grass,NaN,123,100,62,97,81,68,6,False

Note that ```df['Type 1'] == "Grass"``` creates an array of bool values. So, the `loc` method accepts an array of bools as input. Therefore, we can also do things like the following with bool columns:

In [ ]:
df.loc[df['Legendary']]

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Articuno,144,Ice,Flying,90,85,100,95,125,85,1,True
Zapdos,145,Electric,Flying,90,90,85,125,90,100,1,True
Moltres,146,Fire,Flying,90,100,90,125,85,90,1,True
Mewtwo,150,Psychic,NaN,106,110,90,154,90,130,1,True
MewtwoMega Mewtwo X,150,Psychic,Fighting,106,190,100,154,100,130,1,True
...,...,...,...,...,...,...,...,...,...,...,...
Diancie,719,Rock,Fairy,50,100,150,100,150,50,6,True
DiancieMega Diancie,719,Rock,Fairy,50,160,110,160,110,110,6,True
HoopaHoopa Confined,720,Psychic,Ghost,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,720,Psychic,Dark,80,160,60,170,130,80,6,True
Volcanion,721,Fire,Water,80,110,120,130,90,70,6,True

Apply multiple selection criteria using the logical AND operator `&`. Note the parentheses around the `df['Type 1'] == "Fire"` condition. They must be there because the `&` operatore, bitwise AND, has lower precedence than the `==` equality operator.

In [ ]:
df.loc[df['Legendary'] & (df['Type 1'] == "Fire")]

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Moltres,146,Fire,Flying,90,100,90,125,85,90,1,True
Entei,244,Fire,NaN,115,115,85,90,75,100,2,True
Ho-oh,250,Fire,Flying,106,130,90,110,154,90,2,True
Heatran,485,Fire,Steel,91,90,106,130,106,77,4,True
Volcanion,721,Fire,Water,80,110,120,130,90,70,6,True

Logical OR operation:

In [ ]:
df.loc[(df['Type 1'] == 'Grass') | (df['Type 1'] == "Fire")]

After the filtering, one can ask question like what is the highest `"Attack"` of a pokemon that passed.

In [ ]:
fire_legendary_pokemon = df.loc[(df['Type 1'] == 'Fire') & (df['Legendary'] == True)]

if not fire_legendary_pokemon.empty:
  pokemon_with_highest_attack = fire_legendary_pokemon.loc[fire_legendary_pokemon['Attack'].idxmax()]

The operator `~` is the NOT operator. The following expression selects all pokemons that are not Legendary and have the `"HP"` value greater than 150.

In [ ]:
df.loc[~df['Legendary'] & (df['HP'] > 150)]

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Chansey,113,Normal,NaN,250,5,5,35,105,50,1,False
Snorlax,143,Normal,NaN,160,110,65,65,110,30,1,False
Wobbuffet,202,Psychic,NaN,190,33,58,33,58,33,2,False
Blissey,242,Normal,NaN,255,10,10,75,135,55,2,False
Wailord,321,Water,NaN,170,90,45,90,45,60,3,False
Alomomola,594,Water,NaN,165,75,80,40,45,65,5,False

To count the number of `"Type 1"` species, use the `value_counts` method.

In [ ]:
df['Type 1'].value_counts()

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

Select pokemons with Defense in the `(40, 60)` interval:

In [ ]:
new_df = df.loc[df['Defense'].between(40, 60)]
new_df.head()

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,45,49,49,65,65,45,1,False
Charmander,4,Fire,NaN,39,52,43,60,50,65,1,False
Charmeleon,5,Fire,NaN,58,64,58,80,65,80,1,False
Metapod,11,Bug,NaN,50,20,55,25,25,30,1,False
Butterfree,12,Bug,Flying,60,45,50,90,80,70,1,False

When we want pokemons with some specific `"Defense"` values, we use the `isin` method.

In [ ]:
df.loc[df['Defense'].isin([40, 70, 30, 60])].head()

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Weedle,13,Bug,Poison,40,35,30,20,20,50,1,False
Beedrill,15,Bug,Poison,65,90,40,45,80,75,1,False
BeedrillMega Beedrill,15,Bug,Poison,65,150,40,15,80,145,1,False
Pidgey,16,Normal,Flying,40,45,40,35,35,56,1,False
Raticate,20,Normal,NaN,55,81,60,50,70,97,1,False

Select 5% pokemons with the highest speed. The method `quantile` is good for this! (Note that we will not select exactly 5% pokemons because there are several pokemons having the same speed commonly.)

In [ ]:
new_df = df.loc[df['Speed'] > df['Speed'].quantile(0.95)]
print(new_df.shape)
print(df.shape)
print(new_df.shape[0] / df.shape[0])

(37, 11)
(800, 11)
0.04625

## Sorting/Describing Data

To sort the rows according to the `"HP"` value in descending order, do:

In [ ]:
df.sort_values('HP', ascending=False)

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Blissey,242,Normal,NaN,255,10,10,75,135,55,2,False
Chansey,113,Normal,NaN,250,5,5,35,105,50,1,False
Wobbuffet,202,Psychic,NaN,190,33,58,33,58,33,2,False
Wailord,321,Water,NaN,170,90,45,90,45,60,3,False
Alomomola,594,Water,NaN,165,75,80,40,45,65,5,False
...,...,...,...,...,...,...,...,...,...,...,...
Magikarp,129,Water,NaN,20,10,55,15,20,80,1,False
Feebas,349,Water,NaN,20,15,20,10,55,80,3,False
Duskull,355,Ghost,NaN,20,40,90,30,90,25,3,False
Diglett,50,Ground,NaN,10,55,25,35,45,95,1,False
Shedinja,292,Bug,Ghost,1,90,45,30,30,40,3,False

One can also sort according to several characteristics. The rows are sorted primarily according to the `"HP"` value in the descending order. If several pokemons have the same `"HP"` value then they are sorted according to the `"Attack"` value in ascending order.

In [ ]:
df.sort_values(['HP', 'Attack'], ascending=[True, False])

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Shedinja,292,Bug,Ghost,1,90,45,30,30,40,3,False
Diglett,50,Ground,NaN,10,55,25,35,45,95,1,False
Pichu,172,Electric,NaN,20,40,15,35,35,60,2,False
Duskull,355,Ghost,NaN,20,40,90,30,90,25,3,False
Mime Jr.,439,Psychic,Fairy,20,25,45,70,90,60,4,False
...,...,...,...,...,...,...,...,...,...,...,...
Alomomola,594,Water,NaN,165,75,80,40,45,65,5,False
Wailord,321,Water,NaN,170,90,45,90,45,60,3,False
Wobbuffet,202,Psychic,NaN,190,33,58,33,58,33,2,False
Chansey,113,Normal,NaN,250,5,5,35,105,50,1,False
Blissey,242,Normal,NaN,255,10,10,75,135,55,2,False

## Making changes to the data

Create a new column that contains a sum of values from 6 chosen columns:

In [ ]:
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
df['Total']

Name
Bulbasaur                318
Ivysaur                  405
Venusaur                 525
VenusaurMega Venusaur    625
Charmander               309
                        ...
Diancie                  600
DiancieMega Diancie      700
HoopaHoopa Confined      600
HoopaHoopa Unbound       680
Volcanion                600
Name: Total, Length: 800, dtype: int64

Remove the column

In [ ]:
df = df.drop(columns=['Total'])

Create it once again, calculating the same sum as previously:

In [ ]:
df['Total'] = df.iloc[:, 4:10].sum(axis=1)
df['Total']

Reorder columns:

In [ ]:
cols = list(df.columns)
df = df[cols[0:4] + [cols[-1]]+cols[4:11]]

df.head(5)

`reset_index` method updates indeces in a way you choose. `inplace=True` means that no new DataFrame is created. `drop=True` means that any previous index is removed from the DataFrame. With `drop=False`, the old index would be added as a new column to the DataFrame.

In [ ]:
new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 70)]
new_df.reset_index(drop=True, inplace=True)

Conditional changes

In [ ]:
df.loc[df['Attack'] > 100, ['Generation','Legendary']] = [10, True]
df.loc[df['Attack'] > 100]

Generation
10    170
1     134
3     123
5     123
2      92
4      90
6      68
Name: count, dtype: int64

## Creating DataFrames

In [ ]:
# prompt: examples of new dataframe creation

# Method 1: From a dictionary
data = {'col1': [1, 2, 3], 'col2': [4, 5, 6]}
df_from_dict = pd.DataFrame(data)
print("DataFrame from dictionary:\n", df_from_dict)

# Method 2: From a list of lists
data = [[1, 4], [2, 5], [3, 6]]
columns = ['col1', 'col2']
df_from_list = pd.DataFrame(data, columns=columns)
print("\nDataFrame from list of lists:\n", df_from_list)

# Method 3: From a NumPy array
import numpy as np
data = np.array([[1, 4], [2, 5], [3, 6]])
columns = ['col1', 'col2']
df_from_array = pd.DataFrame(data, columns=columns)
print("\nDataFrame from NumPy array:\n", df_from_array)

# Method 4: From another DataFrame (copying or selecting specific columns/rows)
df_copy = df.copy() #creates a copy of the original dataframe named df
print("\nDataFrame copy:\n", df_copy.head()) #print only the first few rows for large datasets
df_subset = df[['Type 1', 'HP']] # Select specific columns into new dataframe
print("\nDataFrame subset:\n", df_subset.head())

# Method 5:  Empty DataFrame with specified column names
df_empty = pd.DataFrame(columns=['A', 'B', 'C'])

# Print the created DataFrames (optional)
print("\nEmpty DataFrame:\n", df_empty)

## Concatenating DataFrames

In [ ]:
# prompt: example of the concat method usage

import pandas as pd

# Sample DataFrames (replace with your actual DataFrames)
data1 = {'col1': [1, 2, 3], 'col2': [4, 5, 6]}
df1 = pd.DataFrame(data1)

data2 = {'col1': [7, 8, 9], 'col2': [10, 11, 12]}
df2 = pd.DataFrame(data2)

# Concatenate DataFrames along rows (axis=0, default)
df_concat_rows = pd.concat([df1, df2])
print("Concatenated along rows:\n", df_concat_rows)
print("Both rows with index 0 are selected with df_concat_rows.loc[0]:\n", df_concat_rows.loc[0])

# Ignoring index
df_ignore_index = pd.concat([df1, df2], ignore_index=True)
print("\nConcatenated along rows with ignored index:\n", df_ignore_index)

# Concatenate DataFrames along columns (axis=1)
df_concat_cols = pd.concat([df1, df2], axis=1)
print("\nConcatenated along columns:\n", df_concat_cols)

# Concatenate with keys to create a hierarchical index
df_concat_keys = pd.concat([df1, df2], keys=['df1', 'df2'])
print("\nConcatenated with keys:\n", df_concat_keys)

# Accessing data with hierarchical index
print("\nAccessing data from hierarchical index:")
print(df_concat_keys.loc['df1']) # Accessing data in df1

# Handling different column names (outer join)
data3 = {'col3': [13, 14, 15], 'col4': [16, 17, 18]}
df3 = pd.DataFrame(data3)

df_concat_outer = pd.concat([df1, df3], axis=1)
print("\nConcatenated with different column names (outer join):\n", df_concat_outer)

# Handling different column names (inner join)
df_concat_inner = pd.concat([df1, df3], axis=1, join="inner") # Only common columns will be kept
print("\nConcatenated with different column names (inner join):\n", df_concat_inner) # Should show nothing as no common columns

## Saving our Data (Exporting into Desired Format)

In [ ]:
# df.to_csv('modified.csv', index=False)

#df.to_excel('modified.xlsx', index=False)

df.to_csv('modified.txt', index=False, sep='\t')

## Plotting

In [ ]:
# prompt: Draw the histogram of the pokemons' HP values. Use dataframe.plot method for this

import matplotlib.pyplot as plt

df['HP'].plot(kind='hist', bins=20)  # Adjust the number of bins as needed
plt.xlabel('HP Value')
plt.ylabel('Frequency')
plt.title('Histogram of Pokemon HP Values')
plt.show()

In [ ]:
df[df['Type 1'] == 'Grass']  .plot(kind='scatter', x='Attack', y='Defense', color='red',  label='Grass')
plt.xlabel('Attack')
plt.ylabel('Defense')
plt.title('Attack vs. Defense')
plt.show()

In [ ]:
# prompt: Draw scatter plot of the Attack vs. Defense values. Use built-in pandas methods for this. Plot it for Grass and Psychic type 1 pokemons to one single figure. Use pandas methods for this!

# Filter for Grass and Psychic type 1 PokÃ©mon
grass_pokemon = df[df['Type 1'] == 'Grass']
psychic_pokemon = df[df['Type 1'] == 'Psychic']

plt.scatter(grass_pokemon['Attack'], grass_pokemon['Defense'], label='Grass', alpha=0.7, color='green')
plt.scatter(psychic_pokemon['Attack'], psychic_pokemon['Defense'], label='Psychic', alpha=0.7, color='violet')

plt.xlabel('Attack')
plt.ylabel('Defense')
plt.legend()
plt.show()

In [ ]:
# prompt: Plot bar chart comparing the HP value of Grass and Fire type 1 pokemons. Make 20 bins in HP and normalize the histograms before plotting


plt.hist([grass_pokemon['HP'], psychic_pokemon['HP']], bins=10, label=['Grass', 'Psychic'], color=['green', 'violet'], density=True)
plt.xlabel('HP Value')
plt.ylabel('Normalized frequency')
plt.legend()
plt.show()

In [ ]:
# prompt: draw frequencies of the different pokemon type 1 values

# Count the frequencies of each Type 1
type1_counts = df['Type 1'].value_counts()

# Create the bar plot
plt.figure(figsize=(10, 10))  # Adjust figure size for better readability
type1_counts.plot(kind='pie')
plt.show()

In [ ]:

# Count the frequencies of each Type 1
type1_counts = df['Type 1'].value_counts()

# Create the bar plot
type1_counts.plot(kind='bar')
plt.xlabel("Pokemon Type 1")
plt.ylabel("Frequency")
plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels for better visibility
plt.tight_layout() # Adjust layout to prevent labels from overlapping
plt.show()